language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pytest-cov
  - pip install codecov
  - python setup.py install
script:
  - pytest --cov=./
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
